#ifndef LIBRARYAYIMEA_GLOBAL_H
#define LIBRARYAYIMEA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRARYAYIMEA_LIBRARY)
#  define LIBRARYAYIMEA_EXPORT Q_DECL_EXPORT
#else
#  define LIBRARYAYIMEA_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRARYAYIMEA_GLOBAL_H
